name: Snuggle
on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Cache
              uses: actions/cache@v2
              with:
                path: ${{ github.workspace }}/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-nuget-
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -   name: Install .NET Core 6
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 6.0.x
                    include-prerelease: true
            -   name: Add msbuild to PATH
                uses: microsoft/setup-msbuild@v1.0.2
            -   name: Build Texture2DDecoderNative (Release, x86)
                run: msbuild Library/AssetStudio/Texture2DDecoderNative/Texture2DDecoderNative.vcxproj /P:Configuration=Release /P:Platform=Win32
            -   name: Build Texture2DDecoderNative (Release, x64)
                run: msbuild Library/AssetStudio/Texture2DDecoderNative/Texture2DDecoderNative.vcxproj /P:Configuration=Release /P:Platform=x64
            -   name: Build Texture2DDecoderNative (Debug, x86)
                run: msbuild Library/AssetStudio/Texture2DDecoderNative/Texture2DDecoderNative.vcxproj /P:Configuration=Debug /P:Platform=Win32
            -   name: Build Texture2DDecoderNative (Debug, x64)
                run: msbuild Library/AssetStudio/Texture2DDecoderNative/Texture2DDecoderNative.vcxproj /P:Configuration=Debug /P:Platform=x64
            -   name: Restore project
                run: dotnet restore
            -   name: Run tests
                run: dotnet test Snuggle.Tests
            -   name: Build Release
                run: dotnet build -c Release -o dist/release
            -   name: Copy Texture2DDecoderNative (Release, x86)
                run: xcopy Library\AssetStudio\Texture2DDecoderNative\bin\Win32\Release\Texture2DDecoderNative.dll dist\release\runtimes\win-x86\native /Y
            -   name: Copy Texture2DDecoderNative (Release, x64)
                run: xcopy Library\AssetStudio\Texture2DDecoderNative\bin\x64\Release\Texture2DDecoderNative.dll dist\release\runtimes\win-x64\native /Y
            -   name: Upload Release
                uses: actions/upload-artifact@v2
                with:
                    name: snuggle-net6-win-x86-64-rel
                    path: dist/release
            -   name: Build ReleaseStandalone
                run: dotnet build Snuggle/Snuggle.csproj -c Release --self-contained -r win-x64 -o dist/release-standalone
            -   name: Copy Texture2DDecoderNative (ReleaseStandalone, x64)
                run: xcopy Library\AssetStudio\Texture2DDecoderNative\bin\x64\Release\Texture2DDecoderNative.dll dist\release-standalone /Y
            -   name: Upload ReleaseStandalone
                uses: actions/upload-artifact@v2
                with:
                    name: snuggle-standalone-win-x64-rel
                    path: dist/release-standalone
            -   name: Build Debug
                run: dotnet build -c Debug -o dist/debug
            -   name: Copy Texture2DDecoderNative (Debug, x86)
                run: xcopy Library\AssetStudio\Texture2DDecoderNative\bin\Win32\Debug\Texture2DDecoderNative.dll dist\debug\runtimes\win-x86\native /Y
            -   name: Copy Texture2DDecoderNative (Debug, x64)
                run: xcopy Library\AssetStudio\Texture2DDecoderNative\bin\x64\Debug\Texture2DDecoderNative.dll dist\debug\runtimes\win-x64\native /Y
            -   name: Upload Debug
                uses: actions/upload-artifact@v2
                with:
                    name: snuggle-net6-win-x86-64-dbg
                    path: dist/debug
